name: Discord Notification

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            {
              "embeds": [
                {
                  "title": "Repository Update!",
                  "description": "${{ github.event_name == 'push' && 'New commit pushed to main.' || 'New release published: ' + github.event.release.tag_name }}",
                  "color": 7506394,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})",
                      "inline": true
                    },
                    {
                      "name": "${{ github.event_name == 'push' && 'Commit' || 'Release' }}",
                      "value": "${{ github.event_name == 'push' && github.sha || github.event.release.html_url }}",
                      "inline": true
                    }
                  ],
                  "timestamp": "${{ github.event.head_commit.timestamp || github.event.release.published_at }}"
                }
              ]
            }
